builddir: build
libs:
    work:
        -  files:
                - ahbrom.vhd
                - config.vhd
                - leon3mp.vhd
                - testbench.vhd
        -   prefix: GRLIB_ROOT
            path: lib/work
            files:
                - debug/debug.vhd
    grlib:  
        prefix: GRLIB_ROOT
        path: lib/grlib
        files:
            - stdlib/version.vhd
            - stdlib/config_types.vhd
            - stdlib/config.vhd
            - stdlib/stdlib.vhd
            - stdlib/stdio.vhd
            - stdlib/testlib.vhd
            - util/util.vhd
            - sparc/sparc.vhd
            - sparc/sparc_disas.vhd
            - sparc/cpu_disas.vhd
            - riscv/riscv.vhd
            - riscv/riscv_disas.vhd
            - riscv/cpu_disas.vhd
            - modgen/multlib.vhd
            - modgen/leaves.vhd
            - amba/amba.vhd
            - amba/devices.vhd
            - amba/defmst.vhd
            - amba/apbctrl.vhd
            - amba/apbctrlx.vhd
            - amba/apbctrlsp.vhd
            - amba/apbctrldp.vhd
            - amba/apbctrl3p.vhd
            - amba/apbctrl4p.vhd
            - amba/ahbctrl.vhd
            - amba/dma2ahb_pkg.vhd
            - amba/dma2ahb.vhd
            - amba/ahbmst.vhd
            - amba/ahblitm2ahbm.vhd
            - amba/dma2ahb_tp.vhd
            - amba/amba_tp.vhd
            - dftlib/dftlib.vhd
            - dftlib/trstmux.vhd
            - dftlib/synciotest.vhd
            - generic_bm/generic_bm_pkg.vhd
            - generic_bm/ahb_be.vhd
            - generic_bm/axi4_be.vhd
            - generic_bm/bmahbmst.vhd
            - generic_bm/bm_fre.vhd
            - generic_bm/bm_me_rc.vhd
            - generic_bm/bm_me_wc.vhd
            - generic_bm/fifo_control_rc.vhd
            - generic_bm/fifo_control_wc.vhd
            - generic_bm/generic_bm_ahb.vhd
            - generic_bm/generic_bm_axi.vhd
    techmap:
        prefix: GRLIB_ROOT
        path: lib/techmap
        files:
            - gencomp/gencomp.vhd
            - gencomp/netcomp.vhd
            - alltech/allclkgen.vhd
            - alltech/allddr.vhd
            - alltech/allmem.vhd
            - alltech/allmul.vhd
            - alltech/allpads.vhd
            - alltech/alltap.vhd
            - inferred/memory_inferred.vhd
            - inferred/ddr_inferred.vhd
            - inferred/mul_inferred.vhd
            - inferred/ddr_phy_inferred.vhd
            - inferred/ddrphy_datapath.vhd
            - inferred/fifo_inferred.vhd
            - inferred/sim_pll.vhd
            - inferred/lpddr2_phy_inferred.vhd
            - maps/techbuf.vhd
            - maps/clkgen.vhd
            - maps/clkmux.vhd
            - maps/clkinv.vhd
            - maps/clkand.vhd
            - maps/grgates.vhd
            - maps/ddr_ireg.vhd
            - maps/ddr_oreg.vhd
            - maps/clkpad.vhd
            - maps/clkpad_ds.vhd
            - maps/inpad.vhd
            - maps/inpad_ds.vhd
            - maps/iodpad.vhd
            - maps/iopad.vhd
            - maps/iopad_ds.vhd
            - maps/lvds_combo.vhd
            - maps/odpad.vhd
            - maps/outpad.vhd
            - maps/outpad_ds.vhd
            - maps/toutpad.vhd
            - maps/toutpad_ds.vhd
            - maps/skew_outpad.vhd
            - maps/ddrphy.vhd
            - maps/syncram.vhd
            - maps/syncram64.vhd
            - maps/syncram_2p.vhd
            - maps/syncram_dp.vhd
            - maps/syncfifo_2p.vhd
            - maps/regfile_3p.vhd
            - maps/tap.vhd
            - maps/nandtree.vhd
            - maps/grlfpw_net.vhd
            - maps/grfpw_net.vhd
            - maps/leon3_net.vhd
            - maps/leon4_net.vhd
            - maps/mul_61x61.vhd
            - maps/cpu_disas_net.vhd
            - maps/ringosc.vhd
            - maps/grpci2_phy_net.vhd
            - maps/system_monitor.vhd
            - maps/inpad_ddr.vhd
            - maps/outpad_ddr.vhd
            - maps/iopad_ddr.vhd
            - maps/syncram128bw.vhd
            - maps/syncram256bw.vhd
            - maps/syncram128.vhd
            - maps/syncram156bw.vhd
            - maps/techmult.vhd
            - maps/spictrl_net.vhd
            - maps/scanreg.vhd
            - maps/syncrambw.vhd
            - maps/syncram_2pbw.vhd
            - maps/sdram_phy.vhd
            - maps/syncreg.vhd
            - maps/serdes.vhd
            - maps/iopad_tm.vhd
            - maps/toutpad_tm.vhd
            - maps/memrwcol.vhd
            - maps/cdcbus.vhd
    eth:
        prefix: GRLIB_ROOT
        path: lib/eth
        files:
            - comp/ethcomp.vhd
            - core/greth_pkg.vhd
            - core/eth_rstgen.vhd
            - core/eth_edcl_ahb_mst.vhd
            - core/eth_ahb_mst.vhd
            - core/greth_tx.vhd
            - core/greth_rx.vhd
            - core/grethc.vhd
            - wrapper/greth_gen.vhd
    opencores:
        prefix: GRLIB_ROOT
        path: lib/opencores
        files:
            - i2c/i2c_master_bit_ctrl.vhd
            - i2c/i2c_master_byte_ctrl.vhd
            - i2c/i2coc.vhd
            - ge_1000baseX/ge_1000baseX_comp.vhd
    gaisler:
        prefix: GRLIB_ROOT
        path: lib/gaisler
        files:
            - arith/arith.vhd
            - arith/mul32.vhd
            - arith/div32.vhd
            - memctrl/memctrl.vhd
            - memctrl/sdctrl.vhd
            - memctrl/sdctrl64.vhd
            - memctrl/sdmctrl.vhd
            - memctrl/srctrl.vhd
            - srmmu/mmuconfig.vhd
            - srmmu/mmuiface.vhd
            - srmmu/libmmu.vhd
            - srmmu/mmutlbcam.vhd
            - srmmu/mmulrue.vhd
            - srmmu/mmulru.vhd
            - srmmu/mmutlb.vhd
            - srmmu/mmutw.vhd
            - srmmu/mmu.vhd
            - leon3/leon3.vhd
            - leon3/grfpushwx.vhd
            - leon3v3/tbufmem.vhd
            - leon3v3/tbufmem_2p.vhd
            - leon3v3/dsu3x.vhd
            - leon3v3/dsu3.vhd
            - leon3v3/dsu3_mb.vhd
            - leon3v3/libfpu.vhd
            - leon3v3/libiu.vhd
            - leon3v3/libcache.vhd
            - leon3v3/libleon3.vhd
            - leon3v3/regfile_3p_l3.vhd
            - leon3v3/mmu_acache.vhd
            - leon3v3/mmu_icache.vhd
            - leon3v3/mmu_dcache.vhd
            - leon3v3/cachemem.vhd
            - leon3v3/mmu_cache.vhd
            - leon3v3/grfpwx.vhd
            - leon3v3/grlfpwx.vhd
            - leon3v3/iu3.vhd
            - leon3v3/proc3.vhd
            - leon3v3/grfpwxsh.vhd
            - leon3v3/leon3x.vhd
            - leon3v3/leon3cg.vhd
            - leon3v3/leon3s.vhd
            - leon3v3/leon3sh.vhd
            - leon3v3/l3stat.vhd
            - leon3v3/cmvalidbits.vhd
            - leon4/leon4.vhd
            - irqmp/irqmp.vhd
            - irqmp/irqamp.vhd
            - irqmp/irqmp_bmode.vhd
            - l2cache/pkg/l2cache.vhd
            - canfd/canfd.vhd
            - axi/axi.vhd
            - axi/ahbm2axi.vhd
            - axi/ahbm2axi3.vhd
            - axi/ahbm2axi4.vhd
            - axi/axinullslv.vhd
            - axi/ahb2axib.vhd
            - axi/ahb2axi3b.vhd
            - axi/ahb2axi4b.vhd
            - axi/ahb2axi_l.vhd
            - misc/misc.vhd
            - misc/rstgen.vhd
            - misc/gptimer.vhd
            - misc/ahbram.vhd
            - misc/ahbdpram.vhd
            - misc/ahbtrace_mmb.vhd
            - misc/ahbtrace_mb.vhd
            - misc/ahbtrace.vhd
            - misc/grgpio.vhd
            - misc/ahbstat.vhd
            - misc/logan.vhd
            - misc/apbps2.vhd
            - misc/charrom_package.vhd
            - misc/charrom.vhd
            - misc/apbvga.vhd
            - misc/svgactrl.vhd
            - misc/grsysmon.vhd
            - misc/gracectrl.vhd
            - misc/grgpreg.vhd
            - misc/ahb_mst_iface.vhd
            - misc/grgprbank.vhd
            - misc/grversion.vhd
            - misc/apb3cdc.vhd
            - misc/ahbsmux.vhd
            - misc/ahbmmux.vhd
            - misc/grtachom.vhd
            - net/net.vhd
            - uart/uart.vhd
            - uart/libdcom.vhd
            - uart/apbuart.vhd
            - uart/apbuart_16550.vhd
            - uart/dcom.vhd
            - uart/dcom_uart.vhd
            - uart/ahbuart.vhd
            - sim/sim.vhd
            - sim/sram.vhd
            - sim/sram16.vhd
            - sim/phy.vhd
            - sim/ser_phy.vhd
            - sim/ahbrep.vhd
            - sim/delay_wire.vhd
            - sim/pwm_check.vhd
            - sim/ramback.vhd
            - sim/slavecheck_slv.vhd
            - sim/ddrram.vhd
            - sim/ddr2ram.vhd
            - sim/ddr3ram.vhd
            - sim/sdrtestmod.vhd
            - sim/ahbram_sim.vhd
            - sim/aximem.vhd
            - sim/axirep.vhd
            - sim/axixmem.vhd
            - sim/sramtestmod.vhd
            - sim/delay_wire2.vhd
            - sim/dfi_phy_sim.vhd
            - sim/dfi_phy_sim_fr.vhd
            - jtag/jtag.vhd
            - jtag/libjtagcom.vhd
            - jtag/jtagcom.vhd
            - jtag/bscanregs.vhd
            - jtag/bscanregsbd.vhd
            - jtag/jtagcom2.vhd
            - jtag/ahbjtag.vhd
            - jtag/ahbjtag_bsd.vhd
            - jtag/jtagcomrv.vhd
            - jtag/ahbjtagrv.vhd
            - jtag/jtagtst.vhd
            - jtag/jtag_rv.vhd
            - greth/ethernet_mac.vhd
            - greth/greth.vhd
            - greth/greth_mb.vhd
            - greth/greth_gbit.vhd
            - greth/greths.vhd
            - greth/greth_gbit_mb.vhd
            - greth/greths_mb.vhd
            - greth/grethm.vhd
            - greth/grethm_mb.vhd
            - greth/adapters/rgmii.vhd
            - greth/adapters/rgmii_kc705.vhd
            - greth/adapters/rgmii_series7.vhd
            - greth/adapters/rgmii_series6.vhd
            - greth/adapters/comma_detect.vhd
            - greth/adapters/sgmii.vhd
            - greth/adapters/elastic_buffer.vhd
            - greth/adapters/gmii_to_mii.vhd
            - greth/adapters/word_aligner.vhd
            - ddr/ddrpkg.vhd
            - ddr/ddrintpkg.vhd
            - ddr/ddrphy_wrap.vhd
            - ddr/ddr2spax_ahb.vhd
            - ddr/ddr2spax_ddr.vhd
            - ddr/ddr2buf.vhd
            - ddr/ddr2spax.vhd
            - ddr/ddr2spa.vhd
            - ddr/ddr1spax.vhd
            - ddr/ddr1spax_ddr.vhd
            - ddr/ddrspa.vhd
            - ddr/ahb2mig_7series_pkg.vhd
            - ddr/ahb2mig_7series.vhd
            - ddr/ahb2mig_7series_ddr2_dq16_ad13_ba3.vhd
            - ddr/ahb2mig_7series_ddr3_dq16_ad15_ba3.vhd
            - ddr/ahb2mig_7series_cpci_xc7k.vhd
            - ddr/ahb2axi_mig_7series.vhd
            - ddr/axi_mig_7series.vhd
            - ddr/ahb2avl_async.vhd
            - ddr/ahb2avl_async_be.vhd
            - i2c/i2c.vhd
            - i2c/i2cmst.vhd
            - i2c/i2cmst_gen.vhd
            - i2c/i2cslv.vhd
            - i2c/i2c2ahbx.vhd
            - i2c/i2c2ahb.vhd
            - i2c/i2c2ahb_apb.vhd
            - i2c/i2c2ahb_gen.vhd
            - i2c/i2c2ahb_apb_gen.vhd
            - spi/spi.vhd
            - spi/spimctrl.vhd
            - spi/spictrlx.vhd
            - spi/spictrl.vhd
            - spi/spi2ahbx.vhd
            - spi/spi2ahb.vhd
            - spi/spi2ahb_apb.vhd
            - spi/spi_flash.vhd
            - nand/nandpkg.vhd
            - grdmac/grdmac_pkg.vhd
            - grdmac/apbmem.vhd
            - grdmac/grdmac_ahbmst.vhd
            - grdmac/grdmac_alignram.vhd
            - grdmac/grdmac.vhd
            - grdmac/grdmac_1p.vhd
            - grdmac2/grdmac2_pkg.vhd
            - grdmac2/grdmac2_apb.vhd
            - grdmac2/mem2buf.vhd
            - grdmac2/buf2mem.vhd
            - grdmac2/grdmac2_ctrl.vhd
            - grdmac2/grdmac2.vhd
            - grdmac2/grdmac2_ahb.vhd
            - grdmac2/grdmac2_acc.vhd
            - grdmac2/grdmac2_axi.vhd
            - subsys/subsys.vhd
            - subsys/leon_dsu_stat_base.vhd
            - plic/plic.vhd
            - plic/grplic.vhd
            - plic/plic_encoder.vhd
            - plic/plic_gateway.vhd
            - plic/plic_target.vhd
            - plic/grplic_ahb.vhd
            - aplic/aplic.vhd
            - aplic/graplic_ahb.vhd
    esa:
        prefix: GRLIB_ROOT
        path: lib/esa
        files:
            - memoryctrl/memoryctrl.vhd
            - memoryctrl/mctrl.vhd
    fmf:
        prefix: GRLIB_ROOT
        path: lib/fmf
        files:
            - utilities/conversions.vhd
            - utilities/gen_utils.vhd
            - flash/flash.vhd
            - flash/s25fl064a.vhd
            - flash/m25p80.vhd
            - fifo/idt7202.vhd
    gsi:
        prefix: GRLIB_ROOT
        path: lib/gsi
        files:
            - ssram/functions.vhd
            - ssram/core_burst.vhd
            - ssram/g880e18bt.vhd
    cypress:
        prefix: GRLIB_ROOT
        path: lib/cypress
        files:
            - ssram/components.vhd
            - ssram/package_utility.vhd
            - ssram/cy7c1354b.vhd
            - ssram/cy7c1380d.vhd
    micron:
        prefix: GRLIB_ROOT
        path: lib/micron
        files:
            - sdram/components.vhd
            - sdram/mt48lc16m16a2.vhd
