builddir: build
libs:
    work:
        -  files:
                - ahbrom.vhd
                - config.vhd
                - leon3mp.vhd
                - testbench.vhd
        -   prefix: GRLIB_ROOT
            path: lib/work
            files:
                - debug/debug.vhd
    grlib:  
        prefix: GRLIB_ROOT
        path: lib/grlib
        files:
            - stdlib/version.vhd
            - stdlib/config_types.vhd
            - stdlib/config.vhd
            - stdlib/stdlib.vhd
            - stdlib/stdio.vhd
            - stdlib/testlib.vhd
            - sparc/sparc.vhd
            - sparc/sparc_disas.vhd
            - modgen/multlib.vhd
            - amba/amba.vhd
            - amba/devices.vhd
    techmap:
        prefix: GRLIB_ROOT
        path: lib/techmap
        files:
            - gencomp/gencomp.vhd
            - gencomp/netcomp.vhd
            - alltech/allclkgen.vhd
            - alltech/allmem.vhd
            - alltech/allmul.vhd
            - alltech/allpads.vhd
            - alltech/alltap.vhd
    gaisler:
        prefix: GRLIB_ROOT
        path: lib/gaisler
        files:
            - arith/arith.vhd
            - arith/mul32.vhd
            - arith/div32.vhd
            - memctrl/memctrl.vhd
            - srmmu/mmuconfig.vhd
            - srmmu/mmuiface.vhd
            - srmmu/libmmu.vhd
            - srmmu/mmutlbcam.vhd
            - srmmu/mmulrue.vhd
            - srmmu/mmulru.vhd
            - srmmu/mmutlb.vhd
            - srmmu/mmutw.vhd
            - srmmu/mmu.vhd
            - leon3/leon3.vhd
            - leon3/grfpushwx.vhd
            - leon3v3/tbufmem.vhd
            - leon3v3/tbufmem_2p.vhd
            - leon3v3/dsu3x.vhd
            - leon3v3/dsu3.vhd
            - leon3v3/dsu3_mb.vhd
            - leon3v3/libfpu.vhd
            - leon3v3/libiu.vhd
            - leon3v3/libcache.vhd
            - leon3v3/libleon3.vhd
            - leon3v3/regfile_3p_l3.vhd
            - leon3v3/mmu_acache.vhd
            - leon3v3/mmu_icache.vhd
            - leon3v3/mmu_dcache.vhd
            - leon3v3/cachemem.vhd
            - leon3v3/mmu_cache.vhd
            - leon3v3/grfpwx.vhd
            - leon3v3/grlfpwx.vhd
            - leon3v3/iu3.vhd
            - leon3v3/proc3.vhd
            - leon3v3/grfpwxsh.vhd
            - leon3v3/leon3x.vhd
            - leon3v3/leon3cg.vhd
            - leon3v3/leon3s.vhd
            - leon3v3/leon3sh.vhd
            - leon3v3/l3stat.vhd
            - leon3v3/cmvalidbits.vhd
            - leon4/leon4.vhd
            - irqmp/irqmp.vhd
            - irqmp/irqamp.vhd
            - irqmp/irqmp_bmode.vhd
            - l2cache/pkg/l2cache.vhd
            - misc/misc.vhd
            - misc/rstgen.vhd
            - misc/gptimer.vhd
            - misc/ahbram.vhd
            - uart/uart.vhd
            - uart/libdcom.vhd
            - uart/apbuart.vhd
            - uart/apbuart_16550.vhd
            - uart/dcom.vhd
            - uart/dcom_uart.vhd
            - uart/ahbuart.vhd
            - sim/sim.vhd
            - sim/uartprint.vhd
            - jtag/jtag.vhd
            - jtag/libjtagcom.vhd
            - jtag/jtagcom2.vhd
    esa:
        prefix: GRLIB_ROOT
        path: lib/esa
        files:
            - memoryctrl/memoryctrl.vhd
            - memoryctrl/mctrl.vhd
    micron:
        prefix: GRLIB_ROOT
        path: lib/micron
        files:
            - sdram/components.vhd
